language: php
php:
  - 7.1
  - 7.2
  - nightly
matrix:
  fast_finish: true
  allow_failures:
     - php: nightly
install:
  - composer install --no-interaction --prefer-source
script:
  - composer test
env:
  global:
    - APP_ENV=test
    - APP_DEBUG=true
