language: php
php:
  - 7.1
  - 7.2
  - nightly
matrix:
  fast_finish: true
  allow_failures:
     - php: nightly
install:
  - composer install --no-interaction --prefer-source
script:
  - composer test
after_success:
  - travis_retry php vendor/bin/php-coveralls -v
